---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
      Naming/ShortVariable:
        enabled: false
  phpcodesniffer:
    enabled: true
    config:
      standard: PSR1,PSR2
ratings:
  paths:
  - "**.php"
exclude_paths:
  - spec/
  - vendor/
