language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'

install: composer install --prefer-source

script:
  - ./vendor/bin/phpspec run -c .phpspec.coverage-ci.yml
  - bash <(curl -s https://codecov.io/bash)
  
after_success:
  - wget https://github.com/humbug/box/releases/download/3.1.2/box.phar
  - php box.phar compile --no-interaction

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: qBUwdw6s0DoRMaY2utuXmKYbyC1TiusO9aZh6OtxUKtLKwQKBjzGKaxvwPw9S5pojCcVySy1PrsKpKq4hONpO4qAO6ofMFiWEEiSjAcjd3YIL5rvfzn9iPmsnjW6mmzqSBqsfagSzduCGudqxN40XWfCP1ZFaKNm+MY7r2islrgaWNb9A/elF4nhEA8dQKxpqPs7Usaym0LaBOBj+agR5jwIygmMRGqJMvOaaPjEN31YTEGt3Rlsnr1SjnxBAyyPDuyCf3Hi4JOSgobWcFZbTs/tOAn8G+7ws+3Ow0KVSTYO7PuLS9CK6d4/8UkNXbOeBSycTXqW3z2G7NoKwQf5izTNPvfNuj9yfs1aI4PIkUPmLySEcJ0xjk8g02kFFyIdC+9aZiI9EyeazyBxyY5518nf0QdoErAxIqhuVYrOJ4xQQtQ1jDQ5JsavB1wHBhrw/4Up9OjESLV335Zb5zoivzVJ+lmi/wf2RLnm9Q8IUvBq8YSgufjXawQteYbDgSPLBqnB7PndArILQUHiPGenv5qj1V0Q9KldwE9jBlIQP3IEt51LykrkJ3HPNX/E9U1JB3ZY2kQWd/VlMp21Y2qAAMMutroxQpcr8uWxW40+gB3MLnw69zz+9SBG8aRWYRQBRiV+WlMOXg0y+ZjuZIOw7BUD45leFWPMeSjK9iIPjoM=
  file: dais.phar
  on:
    repo: xendk/dais
    tags: true
    php: '5.6'
